export type Input = Node | HTMLCollection | Array<Node> | String;

export type Core = {
    (parameter: Input): QueryResult;
    create(tag: string): QueryResult;
    fromHTML(html: string): QueryResult;
    merge(...arguments_: Array<QueryResult>): QueryResult;
    equal(first: QueryResult, second: QueryResult): boolean;
};

export type QueryResult = {
    node: HTMLElement[];
    [Symbol.iterator](): IterableIterator<QueryResult>;
    [index: number]: QueryResult;
    length: number;
    forEach(
        handler: (item: QueryResult, index: number, array: QueryResult) => any
    ): QueryResult;
    text(): string;
    text(string: string): QueryResult;
    class(): string;
    class(className: string): QueryResult;
    id(): string;
    id(id: string): QueryResult;
    addClass(className: string): QueryResult;
    removeClass(className: string): QueryResult;
    toggleClass(className: string): QueryResult;
    hasClass(className: string): boolean;
    prop(key: string): string;
    prop(key: string, value: string): QueryResult;
    attr(key: string): string;
    attr(key: string, value: string): QueryResult;
    html(): string;
    html(html: string): QueryResult;
    width(): number;
    height(): number;
    innerWidth(): number;
    innerHeight(): number;
    css(key: string): string;
    css(key: string, value: string): QueryResult;
    style(key: string): string;
    style(key: string, value: string): QueryResult;
    event(event: string, handler: (event: CustomEvent) => any): QueryResult;
    on(event: string, handler: (event: CustomEvent) => any): QueryResult;
    trigger(event: string | CustomEvent): QueryResult;
    removeEvent(event: string, handler: (event?: Event) => any): QueryResult;
    blur(handler: (event: FocusEvent) => any): QueryResult;
    focus(handler: (event: FocusEvent) => any): QueryResult;
    focusin(handler: (event: FocusEvent) => any): QueryResult;
    focusout(handler: (event: FocusEvent) => any): QueryResult;
    hover(handler: (event: MouseEvent) => any): QueryResult;
    change(handler: (event: InputEvent) => any): QueryResult;
    click(handler: (event: MouseEvent) => any): QueryResult;
    contextmenu(handler: (event: MouseEvent) => any): QueryResult;
    dblclick(handler: (event: MouseEvent) => any): QueryResult;
    error(handler: (event: UIEvent) => any): QueryResult;
    keydown(handler: (event: KeyboardEvent) => any): QueryResult;
    keypress(handler: (event: KeyboardEvent) => any): QueryResult;
    keyup(handler: (event: KeyboardEvent) => any): QueryResult;
    mousedown(handler: (event: MouseEvent) => any): QueryResult;
    mouseenter(handler: (event: MouseEvent) => any): QueryResult;
    mouseleave(handler: (event: MouseEvent) => any): QueryResult;
    mousemove(handler: (event: MouseEvent) => any): QueryResult;
    mouseout(handler: (event: MouseEvent) => any): QueryResult;
    mouseover(handler: (event: MouseEvent) => any): QueryResult;
    mouseup(handler: (event: MouseEvent) => any): QueryResult;
    resize(handler: (event: UIEvent) => any): QueryResult;
    scroll(handler: (event: Event) => any): QueryResult;
    select(handler: (event: Event) => any): QueryResult;
    submit(handler: (event: SubmitEvent) => any): QueryResult;
    input(handler: (event: InputEvent) => any): QueryResult;
    focus(): void;
    focusin(): void;
    focusout(): void;
    hover(): void;
    change(): void;
    click(): void;
    contextmenu(): void;
    dblclick(): void;
    error(): void;
    keydown(): void;
    keypress(): void;
    keyup(): void;
    mousedown(): void;
    mouseenter(): void;
    mouseleave(): void;
    mousemove(): void;
    mouseout(): void;
    mouseover(): void;
    mouseup(): void;
    resize(): void;
    scroll(): void;
    select(): void;
    submit(): void;
    input(): void;
    parent(): QueryResult;
    child(): QueryResult;
    firstChild(): QueryResult;
    firstChild(queryResult: QueryResult): QueryResult;
    lastChild(): QueryResult;
    lastChild(queryResult: QueryResult): QueryResult;
    hasChild(): boolean;
    before(queryResult: QueryResult): QueryResult;
    after(queryResult: QueryResult): QueryResult;
    remove(): QueryResult;
    index(): number;
    next(): QueryResult;
    prev(): QueryResult;
    siblings(): QueryResult;
    append(queryResult: QueryResult): QueryResult;
    value(): string;
    value(key: string): QueryResult;
};

declare const core: Core;

export default core;
